language: node_js
node_js:
- 'node'
env:
  - CI=false
cache:
  directories:
    - node_modules
install:
  - npm install
  - npm run build
script:
  - npm test
deploy:
  provider: surge
  project: ./build/
